spring:
  redis:
    host: 192.168.1.124
    port: 6379
  datasource:
      url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&serverTimezone=GMT%2B8
      username: root
      password: 123456
  jpa:
      database: mysql
      show-sql: true
      #Hibernate ddl auto(validate|create|create-drop|update)
      hibernate:
        ddl-auto: update